// DO NOT EDIT — generated by `bin/rails mcp:generate`. Re-run to update.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"]
  }
});
