// DO NOT EDIT — generated by `bin/rails mcp:generate`. Re-run to update.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

describe("flux-kontext stdio MCP server", () => {
  let client: Client | undefined;
  let transport: StdioClientTransport | undefined;
  let tempHome: string | undefined;

  afterEach(async () => {
    await client?.close();
    await transport?.close();
    if (tempHome) {
      fs.rmSync(tempHome, { recursive: true, force: true });
    }
    client = undefined;
    transport = undefined;
    tempHome = undefined;
  });

  it("exposes the model-line tools over the real stdio transport", async () => {
    const tsxPath = [
      path.resolve("node_modules/.bin/tsx"),
      path.resolve("../../node_modules/.bin/tsx")
    ].find((candidate) => fs.existsSync(candidate));
    expect(tsxPath).toBeDefined();
    tempHome = fs.mkdtempSync(path.join(os.tmpdir(), "runapi-mcp-home-"));

    client = new Client({ name: "flux-kontext-mcp-test", version: "0.1.0" });
    transport = new StdioClientTransport({
      command: tsxPath!,
      args: ["src/index.ts"],
      cwd: process.cwd(),
      stderr: "pipe",
      env: {
        HOME: tempHome,
        PATH: process.env.PATH || ""
      }
    });

    await client.connect(transport);

    const tools = await client.listTools();
    const names = tools.tools.map((tool) => tool.name).sort();
    expect(names).toEqual(["check_pricing","get_task","text_to_image"]);

    const pricing = await client.callTool({ name: "check_pricing", arguments: {} });
    const content = pricing.content?.[0];
    if (!content || content.type !== "text") {
      throw new Error("Expected text tool response");
    }
    expect(JSON.parse(content.text)).toMatchObject({ supported: true });
  });
});
