#!/usr/bin/env node
// DO NOT EDIT — generated by `bin/rails mcp:generate`. Re-run to update.
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { createServer } from "./server.js";

const server = createServer();
await server.connect(new StdioServerTransport());
